GET /api/v1/me HTTP/1.1
host: {{host}}
nwtoken: {{NW_TOKEN}}
mainlanguage: ms

###

GET /api/v1/me/name HTTP/1.1
host: {{host}}
nwtoken: {{NW_TOKEN}}
mainlanguage: zh



###

POST /api/v1/me HTTP/1.1
host: {{host}}
nwtoken: {{NW_TOKEN}}
Content-Type: application/json

{"hello":"world"}

###

POST /api/v1/you HTTP/1.1
host: {{host}}
nwtoken: {{NW_TOKEN}}
Content-Type: application/json
mainlanguage: en

{"age":"24","favouriteColour":"red"}