#DEPLOYMENT
fullnameOverride: image-forge-api
nameOverride: image-forge-api
replicaCount: 10
targetVersion: unversioned
tier: backend

image:
  repository: asia.gcr.io/bustling-sunset-220007/image-forge-api
  tag: master

appContainerPort: 3000

resources:
  limits:
    memory: 500M
    cpu: '250m'
  requests:
    memory: 250M
    cpu: '100m'

startupProbe:
  httpGet:
    path: /api/health
    port: 3000
  failureThreshold: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 5
livenessProbe: {}

envFrom:
  - configMapRef:
      name: image-forge-api-configmap
  - secretRef:
      name: image-forge-api-gcpsm

nodeSelector:
  cloud.google.com/gke-spot: "true"

#SERVICE
service:
  enabled: true
  type: NodePort
  port: 3000

#INGRESS
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: feed-svc-ing
  tls:
    - secretName: ssl-wildcard-newswav
      hosts:
        - image-forge-api.newswav.com
  hosts:
    - host: image-forge-api.newswav.com
      paths:
        - path: /
          pathType: Prefix

#CONFIGMAP
configmap:
  enabled: true
  configmaps:
    - name: image-forge-api-configmap
      data:
        APP_ENV: production
        NODE_ENV: production
        LOG_PRETTIFY: "0"
        REDIS_HOST: "10.148.0.6"
        REDIS_PORT: "6379"
        CORS_DOMAINS: https://adwav-dashboard.web.app,https://newswav.com,https://dashboard.newswav.com,https://ps-website.newswav.com

# HPA
autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 50
  targetCPUUtilizationPercentage: 80
